# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alFh'
alias la='ls -A'
alias l='ls -CF'

# Docker aliases
alias dkr-clean='docker rm $(docker ps -a | grep "Exit" | cut --bytes=-13)'
alias dkr-image-clean='docker rmi $(docker images | grep "<none>" | grep -o -E "[a-z0-9]{12}")'
alias dkr-bash='docker run -t -i -entrypoint="/bin/bash"'
