set background=dark
colors zenburn

set guifont="Source Code Pro Medium 11"
set columns=80 lines=50
set guicursor+=a:blinkon0
set guioptions=aigm
set mousemodel=popup
set scrolloff=6
set sidescrolloff=6
set visualbell
set errorbells
set nocursorline
set nonumber

" Now load specifics to this machine.
if filereadable(expand("~/.gvimlocal"))
    source ~/.gvimlocal
endif
